version: 2.1

orbs:
  android: circleci/android@3.0.0

jobs:
  build-and-test:
    executor: android/android-machine
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Run Lint and Unit Tests
          command: ./gradlew lint test
      - android/create-emulator:
          api-level: 30
          target: default
          abi: x86_64
      - android/wait-for-emulator
      - run:
          name: Run Instrumented Tests
          command: ./gradlew connectedAndroidTest
      - android/delete-emulator
      - android/save-gradle-cache
      - store_test_results:
          path: ~/build/test-results
      - store_artifacts:
          path: ~/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
