version: '2.1'
orbs:
  android: circleci/android@3.0.0

jobs:
  build_and_test:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
      - checkout
      - android/restore_gradle_cache
      - android/restore_build_cache
      - android/run_tests
      - android/save_gradle_cache:
          cache_prefix: v1a
          
      - save_build_cache

workflows:
  build_and_test_workflow:
    jobs:
      - build_and_test
