version: '2.1'
orbs:
  android: circleci/android@3.0.0

jobs:
  build_and_test:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
      - checkout
      - android/restore_gradle_cache
      - android/restore_build_cache

      - android/run_unit_tests:
          gradle_task: test

      - android/build_gradle:
          gradle_task: assembleDebug

      - store_test_results:
          path: '**/build/test-results/testDebugUnitTest'

      - store_artifacts:
          path: '**/build/outputs/apk/debug/*.apk'

      - android/save_gradle_cache:
          cache_prefix: v1a
          
      - save-build-cache

workflows:
  build_and_test_workflow:
    jobs:
      - build_and_test
